version: 2
jobs:
  jsbuild:
    docker:
      - image: circleci/node:9.7.1-stretch-browsers
    steps:
      - run:
          name: Download and unpack UI
          command: cd /tmp; wget https://github.com/cagedtornado/centralconfig-ui/archive/master.zip; unzip master.zip; cp -r centralconfig-ui-master/. /home/circleci/project/; cd /home/circleci/project;

      # Restore our dependency cache
      - restore_cache:
          keys: 
            - node-cache-{{ checksum "package.json" }}
            - node_cache- 

      # Execute the build process
      - run:
          name: Fetch and Install packages
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: node-cache-{{ checksum "package.json" }}

      - run: 
          name: Create optimized production build
          command: yarn build

      # Execute the packaging process
      - run: 
          name: Emit build number
          command: echo "{\"version\":$CIRCLE_BUILD_NUM}" >> build/build.json

      # Persist the built (unzipped) app to the workspace
      - persist_to_workspace:
          root: .
          paths:
            - build

  build:
    docker:
      - image: circleci/golang:1.9.4
    environment:
      PACKAGE_PATH: "github.com/cagedtornado/centralconfig"
    steps:
      - checkout

      - attach_workspace:
          at: /tmp/workspace

      - run:
         name: Get compiler tool
         command: go get github.com/mitchellh/gox

      - run:
         name: Get static assets compilers
         command: go get github.com/jteeuwen/go-bindata/...;go get github.com/elazarl/go-bindata-assetfs/...;

      - run:
         name: Get windows specific dependencies
         command: env GOOS=windows go get -d -v $PACKAGE_PATH/...

      - run:
         name: Get other dependencies
         command: go get -t -d -v $PACKAGE_PATH/...

      - run: 
         name: Compile the UI to static assets
         command: cd /go/src/github.com/cagedtornado/centralconfig; go-bindata-assetfs -pkg cmd /tmp/workspace/build/...; mv -f bindata.go cmd;

      - run:
         name: Run go vet
         command: go vet -x $PACKAGE_PATH/...

      - run:
         name: Run unit tests
         command: go test -v -race $PACKAGE_PATH/...

      - run:
         name: Create binary for DB testing
         command: go install $PACKAGE_PATH/...

      - run:
         name: Create binaries for release
         command: mkdir -p /tmp/binaries; gox -ldflags "-X $PACKAGE_PATH/cmd.buildVersion=1.0.$CIRCLE_BUILD_NUM -X $PACKAGE_PATH/cmd.commitId=$CIRCLE_SHA1" -arch="!mips !mipsle !mips64 !mips64le" -output "/tmp/binaries/${CIRCLE_PROJECT_REPONAME}_{{.OS}}_{{.Arch}}" $PACKAGE_PATH/...

      # Persist the db testing binary to the workspace
      - persist_to_workspace:
          root: /go/bin
          paths:
            - centralconfig

      # Persist the release binaries to the workspace
      - persist_to_workspace:
          root: /tmp
          paths:
            - binaries

      # Persist the release binaries as artifacts
      - store_artifacts:
          path: /tmp/binaries

  deploy:
    docker:
      - image: circleci/python:3.4-jessie-browsers
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Set path
          command: export PATH=~/bin:$PATH

      - run:
          name: Install AWS tools
          command: |            
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -b ~/bin/aws

      - run: 
          name: Prep Cloudflare for deployment
          command: "curl -X PATCH \"https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/settings/development_mode\" -H \"X-Auth-Email: $CLOUDFLARE_EMAIL\" -H \"X-Auth-Key: $CLOUDFLARE_API_KEY\" -H \"Content-Type: application/json\" --data '{\"value\":\"on\"}'"

      # This expects the environment variables
      # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to be set
      # See http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment 
      # for more information
      - run: 
         name: Push to S3
         command: /home/circleci/bin/aws s3 sync /tmp/workspace/build s3://$S3_DEPLOY_BUCKET --quiet

  release:
    docker:
      - image: circleci/golang:1.9.4
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
         name: Fetch and Install packages
         command: go get github.com/tcnksm/ghr

      - run: 
         name: Push the release to Github
         command: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME v1.0.$CIRCLE_BUILD_NUM /tmp/workspace/dashboard-ui.zip || true

workflows:
  version: 2

  # Build and deploy workflow
  build_deploy:
    jobs:
      - jsbuild
      - build:
          requires:
            - jsbuild
#      - dbtest
#      - dockerbuild:
#          requires:
#            - build
#      - dockerpush:
#          requires:
#            - dockerbuild
#      - release:
#          requires:
#            - build